files:
  - source: /lang_source/ReForged.pot
    translation: /mod_po/%language%_reforged.po
  - source: /lang_source/Island Adventures.pot
    translation: /mod_po/ia_%two_letters_code%.po
  - source: /lang_source/Don't Starve Together.pot
    translation: /modmains/%two_letters_code%.po
